### ISSUE TITLE
谢谢大佬的efi，很好用，有个问题。

### ISSUE THREAD

**Issue by sqh-world** [TokiharaSay/OpenCore-ASUS-ROG-STRIX-B360-I-GAMING-Hackintosh#1]
开机图标很大，怎么改小

**Comment by TokiharaSay** [comment]
> 更新图标，怎么改小

由于我自己是4K屏幕所以我开启了HIDPI 
请更改配置文件中位于
Config–NVRAM–Add-4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14-UIScale这个部分里面的02修改成01
